name: Push to Luarocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request:
  workflow_dispatch:

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          test_interpreters: ""
          dependencies: |
            rocks.nvim >= 2.17.0
          labels: |
            neovim
          detailed_description: |
            rocks-config.nvim is a rocks.nvim utility module for helping to configure
            your Neovim setup.

            Features:
            - Execute a specific Lua file per plugin
            - Automatically invoke the setup() function for every installed plugin
            - Statically configure a plugin using TOML syntax directly from within your rocks.toml
